# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaID', models.CharField(max_length=50, unique=True)),
                ('AreaName', models.CharField(max_length=100)),
                ('AreaSize', models.IntegerField(default=0)),
                ('NoOfPoles', models.IntegerField(default=0)),
                ('AverageWatt', models.IntegerField(default=0)),
                ('PowerSaved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LampInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LightID', models.IntegerField(unique=True)),
                ('ZigbeeID', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('maximumWatt', models.IntegerField(default=0)),
                ('DateOfPlantation', models.DateField(null=True)),
                ('LastDateOfMaintainence', models.DateField(null=True)),
                ('AreaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataview.Area')),
            ],
        ),
        migrations.CreateModel(
            name='RunningLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('InPol1', models.IntegerField(default=0)),
                ('InPol2', models.IntegerField(default=0)),
                ('InPol3', models.IntegerField(default=0)),
                ('InPol4', models.IntegerField(default=0)),
                ('InPol5', models.IntegerField(default=0)),
            ],
        ),
    ]
