# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('LightID', models.IntegerField(default=0)),
                ('AreaID', models.CharField(max_length=100)),
                ('current', models.IntegerField(default=0.1)),
                ('voltage', models.IntegerField(default=0)),
            ],
        ),
    ]
